In [1]:
import numpy as np

In [5]:
arr = np.arange(0,10)

In [6]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
arr[8]

8

In [8]:
arr[1:5]

array([1, 2, 3, 4])

THIS ADDS 100 TO THE FIRST FIVE POSITIONS OF THE ARRAY

In [9]:
arr[0:5]=100

In [10]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9])

In [14]:
slice_of_arr=arr[5:]

In [15]:
slice_of_arr

array([5, 6, 7, 8, 9])

In [16]:
arr[:]=111

In [17]:
arr

array([111, 111, 111, 111, 111, 111, 111, 111, 111, 111])

WARNING! CHANGING THE ORIGNAL ARRAY WILL CHANGE THE SLICE VARIABLE

In [18]:
slice_of_arr

array([111, 111, 111, 111, 111])

In [19]:
arr = np.arange(0,10)

In [20]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [21]:
arr_copy=arr

In [22]:
arr_copy

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [25]:
arr_2d=np.array([[5,10,15],[20,25,30],[35,40,45]])

In [26]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [27]:
arr_2d[1]

array([20, 25, 30])

In [28]:
arr_2d[1][1]

25