In [1]:
import numpy as np

In [2]:
arr = np.arange(11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [3]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [4]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04])

In [5]:
A = np.random.randn(10)
A

array([ 0.35091787, -1.00233688, -0.13965663, -0.95256762, -0.20116757,
       -1.76175398, -0.37847712, -0.3899214 , -0.59480399, -0.12367154])

In [8]:
B = np.random.randn(10)
B

array([ 0.05275825,  1.71483653, -1.39287449,  0.02974666,  0.20855861,
       -1.42114047, -0.37057807,  1.10474997,  0.20460058, -0.83557529])

In [9]:
# Binary Function
np.add(A,B)

array([ 0.40367612,  0.71249965, -1.53253112, -0.92282096,  0.00739104,
       -3.18289446, -0.74905519,  0.71482857, -0.39020342, -0.95924684])

In [10]:
np.maximum(A,B)

array([ 0.35091787,  1.71483653, -0.13965663,  0.02974666,  0.20855861,
       -1.42114047, -0.37057807,  1.10474997,  0.20460058, -0.12367154])

In [11]:
np.minimum(A,B)

array([ 0.05275825, -1.00233688, -1.39287449, -0.95256762, -0.20116757,
       -1.76175398, -0.37847712, -0.3899214 , -0.59480399, -0.83557529])

In [12]:
website = 'https://docs.scipy.org/doc/numpy/reference/ufuncs.html#available-ufuncs'

In [13]:
import webbrowser
webbrowser.open(website)

True